ALPACA_API_KEY = "PKQXL7LF4EAFA6R9VRDS"
ALPACA_SECRET_KEY = "vVnLT4aasb8wJgHPabAXpjxldudLpIdFahKemBDH"
ALPACA_PAPER = true
FINNHUB_API_KEY = "d12nqahr01qmhi3jqje0d12nqahr01qmhi3jqjeg"
ALPACA_TRADING_URL = "https://paper-api.alpaca.markets"
ALPACA_DATA_URL    = "https://data.alpaca.markets"

